# Generated by Django 5.0.3 on 2024-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_oasuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
