# Generated by Django 5.0.3 on 2024-03-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_oasuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oasuser',
            old_name='first_name',
            new_name='fName',
        ),
        migrations.RenameField(
            model_name='oasuser',
            old_name='last_name',
            new_name='lName',
        ),
        migrations.RenameField(
            model_name='oasuser',
            old_name='phone_number',
            new_name='phoneNo',
        ),
        migrations.RenameField(
            model_name='oasuser',
            old_name='password',
            new_name='userPass',
        ),
    ]
