# Generated by Django 5.0.3 on 2024-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_rename_first_name_oasuser_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='userPass',
            field=models.CharField(max_length=255),
        ),
    ]
