# Generated by Django 5.0.3 on 2024-03-29 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_alter_oasuser_userpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
