# Generated by Django 5.0.3 on 2024-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_oasuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
