# Generated by Django 5.0.3 on 2024-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0013_oasuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
