# Generated by Django 5.0.3 on 2024-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0014_oasuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
