# Generated by Django 5.0.3 on 2024-03-31 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_alter_oasuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='oasuser',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
