# Generated by Django 5.0.3 on 2024-04-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_alter_oasuser_last_login_alter_oasuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
