# Generated by Django 5.0.3 on 2024-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_alter_oasuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
