# Generated by Django 5.0.3 on 2024-04-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0018_alter_oasuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OASauction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.TextField(max_length=100)),
                ('item_cat', models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2')], max_length=50)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10), max_digits=10)),
                ('auction_created_time', models.DateTimeField(auto_now_add=True)),
                ('auction_end_time', models.DateTimeField()),
                ('picture1', models.ImageField(upload_to='auction_pictures/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='auction_pictures/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='auction_pictures/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='auction_pictures/')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_auctions', to='home_page.oasuser')),
                ('current_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidding_auctions', to='home_page.oasuser')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_auctions', to='home_page.oasuser')),
            ],
        ),
    ]
