# Generated by Django 5.0.3 on 2024-04-19 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0019_oasauction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]), max_digits=10),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
