# Generated by Django 5.0.3 on 2024-04-21 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0024_alter_oasauction_auction_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='auction_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
