# Generated by Django 5.0.3 on 2024-04-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0025_alter_oasauction_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='auction_end_time',
            field=models.DateTimeField(),
        ),
    ]
