# Generated by Django 5.0.3 on 2024-04-22 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0026_alter_oasauction_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='auction_created_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 3, 32, 16, 687479, tzinfo=datetime.timezone.utc)),
        ),
    ]
