# Generated by Django 5.0.3 on 2024-04-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0027_alter_oasauction_auction_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='auction_created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
