# Generated by Django 5.0.3 on 2024-04-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0033_oasauction_second_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oasauction',
            name='second_bid',
        ),
    ]
