# Generated by Django 5.0.3 on 2024-04-28 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0034_remove_oasauction_second_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasauction',
            name='second_highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='oasauction',
            name='second_highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page.oasuser'),
        ),
    ]
