# Generated by Django 5.0.3 on 2024-04-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0035_oasauction_second_highest_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OASwatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.oasauction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.oasuser')),
            ],
        ),
    ]
