# Generated by Django 5.0.3 on 2024-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0036_oaswatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasauction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oasauction',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oasauction',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='auction_created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
