# Generated by Django 5.0.3 on 2024-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0037_oasauction_is_completed_oasauction_is_ongoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='auction_pictures/'),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='auction_pictures/'),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='auction_pictures/'),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='auction_pictures/'),
        ),
    ]
