# Generated by Django 5.0.3 on 2024-05-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0038_alter_oasauction_picture1_alter_oasauction_picture2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.oasauction')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.oasuser')),
            ],
        ),
    ]
