# Generated by Django 5.0.3 on 2024-05-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0039_auctionwinner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionWinner',
            new_name='OASauctionWinner',
        ),
    ]
