# Generated by Django 5.0.3 on 2024-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0040_rename_auctionwinner_oasauctionwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasauction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='buyer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oasauctionwinner',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oasuser',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=65, null=True),
        ),
    ]
