# Generated by Django 5.0.3 on 2024-05-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0041_oasauction_comment_oasauctionwinner_buyer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasauctionwinner',
            name='checkout_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
