# Generated by Django 5.0.3 on 2024-05-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0042_oasauctionwinner_checkout_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='oasuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
        migrations.CreateModel(
            name='OAStransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_main', to='home_page.oasuser')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_second', to='home_page.oasuser')),
            ],
        ),
    ]
