# Generated by Django 5.0.3 on 2024-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0044_oastransaction_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='oastransaction',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
