# Generated by Django 5.0.3 on 2024-05-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0046_oasauction_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauctionwinner',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.oasuser'),
        ),
        migrations.AlterField(
            model_name='oasauctionwinner',
            name='winning_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
