# Generated by Django 5.0.3 on 2024-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0050_oasreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oasauction',
            name='item_desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='oasauction',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
